### PR TITLE
Clear cache on upgrade

### LINKED ISSUE #577: Upgrade functionality should clear the cache
Whenever we change the DB version, the system shows a message alerting the user (admin only) to update the db. When this is done, the database is updated, but Cake cache is not. This causes issues because the model objects will now be inconsistent with the db schema. We need to make sure that when updating the DB, we also clear the Cake cache.

Affected Controller: upgrade_controller.php

### PR DESCRIPTION
**Pull request by wynnset**
Add missing line to clear default cache in addition to the custom "Configuration" cache

Fixes #577

### CODE REVIEW

**Comment by wynnset** [comment]
I discovered that we have 2 cache set up, according to config/core.php. One is the default one, and one is the 'configuration' one (a custom cache we had added "for configuration/sys parameters"). Only the "configuration" cache was being cleared, leaving the "default" cache uncleared.

I've now added a line to clear the default cache as well when upgrading, so I think this should do the trick.I have not tested it on verf. We will need to test this somehow on verf and make sure it will work.

**Comment by kitsook** [comment]
The caching issue we encountered was on the DB models stored under `app/tmp/cache/models`.  I believe it is different from the caching provided by `Cache`.  Tried to invoke `Cache::clear` explicitly and the model files are not cleared / updated.

The model cache update is handled by CakePHP.  It can be simulated in dev by turning on/off debug mode (set `IPEER_DEBUG` equal to 0/1/2 in `docker-compose.yml`).  If debug mode is on, CakePHP checks for DB changes frequently (e.g. during page load) and the model files under `app/tmp/cache/models` will be updated.

The `Cache` library is more on the application caching.  Grepping the code, seems that only the system parameter module used the `configuration` cache.  The `default` cache isn't used at all.

**Comment by kitsook** [comment]
I think what we need is to call [`clearCache`](https://api.cakephp.org/2.4/function-clearCache.html#) for `models`.

**Comment by wynnset** [comment]
Good find. I've added clearCache() to be run after the upgrade. Seems like we have to explicitly set the directory to clear, so I've set it to clear the following directories under app/tmp/cache:
- css
- js
- persistent
- models
- views

I think it's OK to clear all of the above when doing an upgrade.

**Comment by wynnset** [comment]
@xcompass maybe we could include this in the release and see if the cache gets cleared (we can manually clear if it doesn't, but our tests showed that it'll work).

**Pull request merged**
